name: flutter_hangman
description: Hangman Game
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rflutter_alert: ^2.0.7
  material_design_icons_flutter: ^7.0.7296
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_spinkit: ^5.2.0
  date_format: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - res/
  fonts:
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf